jenkins:
  systemMessage: "Jenkins instance using Configuration as Code."
  globalNodeProperties:
  - envVars:
      env:
      - key: SOME_ENV_PATH
        value: "/path/to/somewhere"
      - key: AWS_REGION
        value: us-west-2

